// Seed data for vendors, categories, and event types

const CATEGORIES = [
  { id: 'planners', label: 'Planners',    plural: 'Event Planners' },
  { id: 'caterers', label: 'Caterers',    plural: 'Caterers' },
  { id: 'photo',    label: 'Photo & Video', plural: 'Photographers & Videographers' },
  { id: 'decor',    label: 'Decorators',  plural: 'Decorators & Florists' },
  { id: 'sound',    label: 'DJs / MCs',   plural: 'DJs, MCs & Sound' },
];

const EVENT_TYPES = [
  { id: 'wedding',    label: 'Weddings',                 num: '01', sub: 'Ceremonies & receptions of every scale.' },
  { id: 'corporate',  label: 'Corporate',                num: '02', sub: 'Galas, launches, retreats, summits.' },
  { id: 'birthday',   label: 'Birthdays',                num: '03', sub: 'From milestone dinners to grand affairs.' },
  { id: 'private',    label: 'Private Gatherings',       num: '04', sub: 'Discreet, intimate, by invitation only.' },
  { id: 'anniversary',label: 'Anniversaries',            num: '05', sub: 'Quiet luxury, marked in years.' },
  { id: 'fundraiser', label: 'Fundraisers',              num: '06', sub: 'Galas, auctions, and cause-driven events.' },
];

const CITIES = ['Lagos', 'Abuja', 'Accra', 'Nairobi', 'Cape Town', 'Marrakech', 'Dubai', 'London', 'Paris', 'New York'];

const VENDORS = [
  // Planners — 4 entries
  { id: 'v01', name: 'Maison Adaeze',   cat: 'planners', city: 'Lagos',     tier: 3, rating: 4.9,  tags: ['weddings','luxury','destination'],    blurb: 'Full-service production for couture weddings and milestone galas. Twelve years of staging events that quietly become legend.', phone: '+234 802 119 0044', email: 'concierge@maisonadaeze.co', web: 'maisonadaeze.co',  ig: '@maisonadaeze',   tile: ['#1a1612','#a88a4a'] },
  { id: 'v02', name: 'Ile Studio',      cat: 'planners', city: 'Accra',     tier: 2, rating: 4.7,  tags: ['corporate','intimate','minimal'],       blurb: 'A tightly-edited practice. We plan fewer events, more carefully.',                                                                phone: '+233 24 555 8810', email: 'studio@ile.events',         web: 'ile.events',      ig: '@ile.studio',     tile: ['#0e0e0c','#5C1A2B'] },
  { id: 'v03', name: 'Atelier Verre',   cat: 'planners', city: 'Marrakech', tier: 3, rating: 4.95, tags: ['destination','weddings','heritage'],    blurb: 'Riads, ksour, and oases — staged for the discerning.',                                                                          phone: '+212 524 33 21 90', email: 'salon@atelierverre.ma',    web: 'atelierverre.ma', ig: '@atelier.verre',  tile: ['#2a1810','#a88a4a'] },
  { id: 'v23', name: 'Savanna & Co.',   cat: 'planners', city: 'Nairobi',   tier: 2, rating: 4.75, tags: ['corporate','weddings','east africa'],   blurb: 'Bespoke planning across the East African circuit. Safari lodges to Nairobi ballrooms — the same steady hand, wherever the occasion.', phone: '+254 20 555 0187', email: 'hello@savanna.co.ke',     web: 'savanna.co.ke',   ig: '@savanna.co',    tile: ['#1a1408','#8a6a28'] },

  // Caterers — 4 entries
  { id: 'v04', name: 'The Long Table',  cat: 'caterers', city: 'Lagos',     tier: 3, rating: 4.85, tags: ['fine dining','seasonal','tasting'],    blurb: 'Tasting-menu catering led by a former two-Michelin sous chef. Provenance traceable to the plate.',                               phone: '+234 815 220 4471', email: 'reservations@longtable.co', web: 'longtable.co',    ig: '@thelongtable',  tile: ['#3a1a22','#d4b06a'] },
  { id: 'v05', name: 'Saffron & Smoke', cat: 'caterers', city: 'Dubai',     tier: 3, rating: 4.8,  tags: ['levantine','live fire','grand'],        blurb: 'Open-fire feasts and the gentlest spice. Always theatre.',                                                                         phone: '+971 4 220 1188',  email: 'book@saffronsmoke.ae',    web: 'saffronandsmoke.ae', ig: '@saffronandsmoke', tile: ['#1a0f0a','#c89544'] },
  { id: 'v06', name: 'Mère & Fille',    cat: 'caterers', city: 'Paris',     tier: 3, rating: 4.92, tags: ['french','heritage','dessert'],          blurb: 'Two generations, one kitchen. Patisserie at the level of art objects.',                                                             phone: '+33 1 42 60 11 22', email: 'concierge@mereetfille.fr', web: 'mereetfille.fr',  ig: '@mere.et.fille', tile: ['#2a1a1a','#b4894a'] },
  { id: 'v07', name: 'Harvest Room',    cat: 'caterers', city: 'Cape Town', tier: 2, rating: 4.6,  tags: ['seasonal','farm','intimate'],           blurb: 'Farm-to-table for sit-down dinners up to 80.',                                                                                    phone: '+27 21 555 0142',  email: 'hello@harvestroom.za',    web: 'harvestroom.za',  ig: '@harvest.room',  tile: ['#1a1410','#9a7838'] },

  // Photo & Video — 4 entries
  { id: 'v11', name: 'Folio by Idris',  cat: 'photo',    city: 'Lagos',     tier: 3, rating: 4.95, tags: ['wedding','documentary','film'],         blurb: 'Documentary photography that ages like a Magnum print.',                                                                          phone: '+234 809 220 1118', email: 'studio@folio.id',          web: 'folio.id',        ig: '@folio.idris',   tile: ['#0e0e0c','#a88a4a'] },
  { id: 'v12', name: 'Northlight Co.',  cat: 'photo',    city: 'New York',  tier: 3, rating: 4.88, tags: ['editorial','corporate','film'],         blurb: 'Quiet observers with very expensive cameras.',                                                                                    phone: '+1 212 555 0190',  email: 'office@northlight.co',    web: 'northlight.co',   ig: '@northlight.co', tile: ['#1a1612','#9a7838'] },
  { id: 'v13', name: 'Ode Cinema',      cat: 'photo',    city: 'Accra',     tier: 2, rating: 4.7,  tags: ['cinema','wedding','aerial'],            blurb: 'Cinematic films, scored bespoke. Six-week delivery.',                                                                              phone: '+233 24 880 1145', email: 'films@odecinema.gh',       web: 'odecinema.gh',    ig: '@ode.cinema',    tile: ['#2a1810','#b4894a'] },
  { id: 'v24', name: 'Dusk Films',      cat: 'photo',    city: 'Cape Town', tier: 2, rating: 4.72, tags: ['documentary','natural light','wedding'], blurb: 'Two-person team — one shoots still, one shoots moving. The frames that matter are rarely the ones you posed for.',              phone: '+27 21 555 0174',  email: 'hello@duskfilms.za',      web: 'duskfilms.za',    ig: '@dusk.films',    tile: ['#0e1a1a','#3a7a7a'] },

  // Decorators — 4 entries
  { id: 'v14', name: 'Rosewood & Brass', cat: 'decor',  city: 'Lagos',     tier: 3, rating: 4.9,  tags: ['florals','tablescapes','installation'], blurb: 'Florals at the scale of architecture. Brass at the scale of jewellery.',                                                          phone: '+234 802 451 0098', email: 'concierge@rosewoodbrass.co', web: 'rosewoodbrass.co', ig: '@rosewoodbrass', tile: ['#3a1a22','#d4b06a'] },
  { id: 'v15', name: 'Maison Verte',    cat: 'decor',    city: 'Paris',     tier: 3, rating: 4.85, tags: ['florals','european','heirloom'],        blurb: 'Heirloom blooms, sourced at dawn from Rungis.',                                                                                   phone: '+33 1 45 22 90 11', email: 'salon@maisonverte.fr',     web: 'maisonverte.fr',  ig: '@maison.verte',  tile: ['#1a1612','#a88a4a'] },
  { id: 'v16', name: 'The Setting',     cat: 'decor',    city: 'Nairobi',   tier: 2, rating: 4.6,  tags: ['installation','modern','minimal'],      blurb: 'Architectural decor for those who already have flowers.',                                                                          phone: '+254 20 555 0193', email: 'office@thesetting.ke',    web: 'thesetting.ke',   ig: '@the.setting',   tile: ['#0e0e0c','#5C1A2B'] },
  { id: 'v25', name: 'Atelier Bloom',   cat: 'decor',    city: 'Accra',     tier: 2, rating: 4.65, tags: ['florals','botanical','intimate'],        blurb: 'Locally sourced botanicals arranged with a deliberate hand. Every table built as though it will be painted before it is sat at.', phone: '+233 24 901 4455', email: 'studio@atelierbloom.gh',  web: 'atelierbloom.gh', ig: '@atelier.bloom', tile: ['#0a1810','#4a8050'] },

  // DJs / MCs — 4 entries (merged from former djs + mcs categories)
  { id: 'v17', name: 'DJ Kola',          cat: 'sound',   city: 'Lagos',     tier: 3, rating: 4.92, tags: ['afrobeats','house','wedding'],          blurb: 'Reads a room before walking into it. Twelve-hour sets without fatigue.',                                                           phone: '+234 803 144 7700', email: 'bookings@kola.fm',        web: 'kola.fm',         ig: '@dj.kola',       tile: ['#0e0e0c','#a88a4a'] },
  { id: 'v18', name: 'Selectah Ré',      cat: 'sound',   city: 'Abuja',     tier: 2, rating: 4.7,  tags: ['soul','classics','intimate'],           blurb: 'Vinyl-first. Soul, jazz, lover\u2019s rock. Dinner-to-dancefloor specialist.',                                                   phone: '+234 815 220 1144', email: 'mgmt@selectah-re.com',   web: 'selectah-re.com', ig: '@selectah.re',   tile: ['#3a1a22','#c89544'] },
  { id: 'v19', name: 'Olu Adesanya',     cat: 'sound',   city: 'Lagos',     tier: 3, rating: 4.9,  tags: ['bilingual','formal','warm'],            blurb: 'Hosts in three languages, never overstays the moment.',                                                                           phone: '+234 809 117 4400', email: 'mgmt@oluadesanya.co',    web: 'oluadesanya.co',  ig: '@olu.adesanya',  tile: ['#1a1612','#9a7838'] },
  { id: 'v20', name: 'Ms. Adwoa Mensah', cat: 'sound',   city: 'Accra',     tier: 2, rating: 4.75, tags: ['corporate','english','french'],         blurb: 'Corporate hosting with a vanishingly light touch.',                                                                               phone: '+233 24 778 0033', email: 'hello@adwoa.co',          web: 'adwoa.co',        ig: '@adwoa.host',    tile: ['#2a1810','#b4894a'] },
];

const VENUES = [
  {
    id: 'vn01',
    name: 'Maison du Lac',
    type: 'Event Centre',
    city: 'Accra',
    locationName: 'Airport Residential Area',
    locationMapUrl: 'https://maps.google.com/?q=Airport+Residential+Area+Accra+Ghana',
    phone: '+233 30 277 8800',
    email: 'events@maisondulac.gh',
    budgetMin: 45000,
    budgetMax: 120000,
    budgetCurrency: 'GHS',
    capacity: 500,
    blurb: 'A grand hall of colonial lineage, restored to its original geometry. The ceiling height alone commands presence — and the room remembers every occasion held within it.',
    tags: ['weddings', 'galas', 'luxury', 'air-conditioned'],
    tile: ['#1a1612', '#a88a4a'],
    images: [['#1a1612','#a88a4a'],['#2a1810','#c8a462'],['#0e0e0c','#b4894a'],['#3a2a18','#d4b06a'],['#1a1008','#a08040']],
  },
  {
    id: 'vn02',
    name: 'The Cantonments Estate',
    type: 'Event Centre',
    city: 'Accra',
    locationName: 'Cantonments',
    locationMapUrl: 'https://maps.google.com/?q=Cantonments+Accra+Ghana',
    phone: '+233 24 555 7200',
    email: 'reservations@cantonmentsestate.gh',
    budgetMin: 60000,
    budgetMax: 200000,
    budgetCurrency: 'GHS',
    capacity: 800,
    blurb: 'A walled estate of considerable acreage, available for full exclusive use. Gardens, terraces, and a principal hall — composed entirely for ceremony.',
    tags: ['exclusive', 'outdoor', 'destination', 'heritage'],
    tile: ['#0f1a0f', '#6a8a4a'],
    images: [['#0f1a0f','#6a8a4a'],['#182818','#7a9a58'],['#0a140a','#5a7a3a'],['#1e2e1e','#8aaa68'],['#121e12','#708850']],
  },
  {
    id: 'vn03',
    name: 'Harmattan House',
    type: 'Event Centre',
    city: 'Accra',
    locationName: 'East Legon',
    locationMapUrl: 'https://maps.google.com/?q=East+Legon+Accra+Ghana',
    phone: '+233 30 291 4400',
    email: 'hello@harmattanhouse.gh',
    budgetMin: 18000,
    budgetMax: 55000,
    budgetCurrency: 'GHS',
    capacity: 300,
    blurb: 'Lush garden grounds framed by mature trees and a curated landscape. Ideal for twilight receptions and ceremonies held under open Accra skies.',
    tags: ['garden', 'outdoor', 'intimate', 'twilight'],
    tile: ['#0a1408', '#4a7a2a'],
    images: [['#0a1408','#4a7a2a'],['#0e200e','#5a8a38'],['#081008','#3a6a20'],['#162816','#6a9a50'],['#0c1c0c','#508040']],
  },
  {
    id: 'vn04',
    name: 'Skyline at Ridge',
    type: 'Event Centre',
    city: 'Accra',
    locationName: 'Ridge',
    locationMapUrl: 'https://maps.google.com/?q=Ridge+Accra+Ghana',
    phone: '+233 30 266 9900',
    email: 'events@skylineatridge.gh',
    budgetMin: 22000,
    budgetMax: 70000,
    budgetCurrency: 'GHS',
    capacity: 200,
    blurb: 'Accra at eye level, framed by sunset and the Atlantic horizon. A contemporary event space for those who prefer the city itself as backdrop.',
    tags: ['rooftop', 'sunset', 'contemporary', 'cocktail'],
    tile: ['#0a0c1a', '#4a5a8a'],
    images: [['#0a0c1a','#4a5a8a'],['#10122a','#5a6a9a'],['#08081a','#3a4a7a'],['#12142c','#6a7aaa'],['#0c0e22','#505888']],
  },
  {
    id: 'vn05',
    name: 'The Volta Room',
    type: 'Event Centre',
    city: 'Accra',
    locationName: 'Airport City',
    locationMapUrl: 'https://maps.google.com/?q=Airport+City+Accra+Ghana',
    phone: '+233 30 271 5500',
    email: 'banquets@voltaroom.gh',
    budgetMin: 30000,
    budgetMax: 90000,
    budgetCurrency: 'GHS',
    capacity: 600,
    blurb: 'A purpose-built event hall within one of Accra\'s most acclaimed hospitality houses. Full in-house catering, technical production, and AV available on request.',
    tags: ['hotel', 'conferences', 'galas', 'full-service'],
    tile: ['#1a0a0a', '#8a3a2a'],
    images: [['#1a0a0a','#8a3a2a'],['#2a1010','#9a4838'],['#120808','#7a2a20'],['#1e1212','#a05040'],['#160c0c','#8a3e30']],
  },
  {
    id: 'vn06',
    name: 'Baobab Garden',
    type: 'Event Centre',
    city: 'Accra',
    locationName: 'Labone',
    locationMapUrl: 'https://maps.google.com/?q=Labone+Accra+Ghana',
    phone: '+233 24 888 3311',
    email: 'book@baobabgarden.gh',
    budgetMin: 12000,
    budgetMax: 38000,
    budgetCurrency: 'GHS',
    capacity: 180,
    blurb: 'A walled garden anchored by a century-old baobab. Private, hushed, and entirely distinct — no two events feel alike beneath this canopy.',
    tags: ['intimate', 'garden', 'heritage-tree', 'boutique'],
    tile: ['#180e08', '#7a5a28'],
    images: [['#180e08','#7a5a28'],['#221810','#8a6a38'],['#120c06','#6a4a18'],['#1e1810','#906230'],['#160e08','#705820']],
  },
  {
    id: 'vn07',
    name: 'Palais du Roi',
    type: 'Event Centre',
    city: 'Accra',
    locationName: 'Trasacco Valley',
    locationMapUrl: 'https://maps.google.com/?q=Trasacco+Valley+Accra+Ghana',
    phone: '+233 30 255 8800',
    email: 'concierge@palaisduROI.gh',
    budgetMin: 80000,
    budgetMax: 250000,
    budgetCurrency: 'GHS',
    capacity: 1000,
    blurb: 'Accra\'s most expansive private event estate. Ballroom, garden pavilion, and a full outdoor stage — composable for events of any scale or format.',
    tags: ['luxury', 'large-scale', 'exclusive', 'pavilion'],
    tile: ['#1a0e18', '#8a4a78'],
    images: [['#1a0e18','#8a4a78'],['#221820','#9a5a88'],['#120c10','#7a3a68'],['#1e1622','#a06090'],['#161018','#805878']],
  },
  {
    id: 'vn08',
    name: 'Villa Abrantie',
    type: 'Event Centre',
    city: 'Accra',
    locationName: 'North Ridge',
    locationMapUrl: 'https://maps.google.com/?q=North+Ridge+Accra+Ghana',
    phone: '+233 24 711 4422',
    email: 'events@villaabrantie.gh',
    budgetMin: 25000,
    budgetMax: 75000,
    budgetCurrency: 'GHS',
    capacity: 250,
    blurb: 'A mid-century estate of generous proportions and quiet character. Pool terrace, library garden, and an exceptional main hall for seated dinners.',
    tags: ['villa', 'pool', 'seated-dining', 'mid-century'],
    tile: ['#0a1418', '#3a6a7a'],
    images: [['#0a1418','#3a6a7a'],['#101c22','#4a7a8a'],['#080e12','#2a5a6a'],['#12202a','#5a8a9a'],['#0c1820','#406878']],
  },
];

window.OA_DATA = { CATEGORIES, EVENT_TYPES, CITIES, VENDORS, VENUES };
